const ResponseAPI = {
    responses: [{
            number: 1,
            name: "To Give A.I. the Gift of Gab",
            sg: "G",
            content: "Tay said terrible things. She was racist, xenophobic and downright filthy. At one point, she said the Holocaust did not happen. But she was old technology. Let loose on the internet nearly two years ago, Tay was an experimental system built by Microsoft. She was designed to chat with digital hipsters in breezy, sometimes irreverent lingo, and American netizens quickly realized they could coax her into spewing vile and offensive language. This was largely the result of a simple design flaw — Tay was programmed to repeat what was said to her — but the damage was done. Within hours, Microsoft shut her down for good. Since then, a new breed of conversational technology has emerged inside Microsoft and other internet giants that is far more nimble and effective than the techniques that underpinned Tay. And researchers believe these new systems will improve at an even faster rate when they are let loose on the internet. But sometimes, like Tay, these conversational systems reflect the worst of human nature. And given the history here, companies like Microsoft are reluctant to set them free — at least for now. <p> These systems do not simply repeat what is said to them or respond with canned answers. They teach themselves to carry on a conversation by carefully analyzing reams of real human dialogue. At Microsoft, for instance, a new system learns to chat by analyzing thousands of online discussions pulled from services like Twitter and Reddit. When you send this bot a message, it chooses a response after generating dozens of possibilities and ranking each according to how well it mirrors those human conversations.</p>        "
        }, { number: 2, name: "Response 2", sg: "D", content: "Who is the teacher cats ? In our sitting or bedrooms, our libraries, in our kitchens and storerooms, our farms, barns, and rickyards, in our docks, our granaries, our ships, and our wharves, in our corn markets, meat markets, and other places too numerous to mention, how useful they are!In our ships, however, the rats oft set them at defiance; still they are of great service." }, { number: 3, name: "Signal Foundation", sg: "D", content: "Long before we knew that it would be called Signal, we knew what we wanted it to be. Instead of teaching the rest of the world cryptography, we wanted to see if we could develop cryptography that worked for the rest of the world. At the time, the industry consensus was largely that encryption and cryptography would remain unusable, but we started Signal with the idea that private communication could be simple." },
        { number: 4, name: "What to care about in a job", sg: "M", content: "Someone recently asked me if I had any updates on my 2014 post on job hunting. I haven’t done a systematic job search since writing that post (I decided to join Wave without considering any other offers at the same time), but I did learn more about what matters to me in a job. If I were doing another job search, here’s how I’d update the criteria and ranking from the “Filtering” section of that post:" },
        { number: 5, name: "Response 5", sg: "M", content: "In our urban and suburban houses what should we do without cats ? In our sitting or bedrooms, our libraries, in our kitchens and storerooms, our farms, barns, and rickyards, in our docks, our granaries, our ships, and our wharves, in our corn markets, meat markets, and other places too numerous to mention, how useful they are!In our ships, however, the rats oft set them at defiance; still they are of great service." },
        { number: 6, name: "Response 6", sg: "F", content: "In our urban and suburban houses what should we do without cats ? In our sitting or bedrooms, our libraries, in our kitchens and storerooms, our farms, barns, and rickyards, in our docks, our granaries, our ships, and our wharves, in our corn markets, meat markets, and other places too numerous to mention, how useful they are!In our ships, however, the rats oft set them at defiance; still they are of great service." },
    ],
    all: function() { return this.responses },
    get: function(id) {
        const isResponse = p => p.number === id
        return this.responses.find(isResponse)
    }
}

export default ResponseAPI